services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=123
      - MARIADB_DATABASE=db_picpay
      - MARIADB_ROOT_PASSWORD=123
    volumes:
      - db_data:/var/lib/mariadb

volumes:
  db_data: